config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/visit', to: 'static_pages#visit'

  resources :personnels, param: :uname

  resources :articles

  resources :affiliations

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessor :delete_image
  before_save :remove_image

  #Paperclip declarations
  has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => /\Aimage/
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]

  def remove_image
    self.image = nil unless self.delete_image.to_i.zero?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def show
    respond_with(@article)
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :date_of_article, :delete_image, :image)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :image, "Article Image"
    %br
    = f.file_field :image, accept: 'image/png,image/jpeg', class: "article_image"
    = f.hidden_field :delete_image, value: "0"
  .field
    = f.label :date_of_article
    = f.date_select :date_of_article, order: [:month, :day, :year]
  .actions
    = f.submit 'Save'

:coffee
  -# This is here because javascript files served from the asset folder do not have
  -# Access to controller class instance variables
  options = {}
  if #{@article.image.exists?}
    options["initialPreview"] = ["<img src='#{@article.image.url(:large)}' class=\'file-preview-image\' alt=\'Article Image\' title=\'Image\'>"]

  options["showUpload"] = false
  $(".article_image").fileinput options
  
  $('.article_image').on 'filecleared', (event) -> 
    $('#article_delete_image').val "1"
  $('.article_image').on 'fileloaded', (event) -> 
    $('#article_delete_image').val "0"

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1.text-center Institute of Behavioral Science
- @articles.each do |article|
  .clearfix
    %h3.text-center
      = link_to article.title, article
    = article.date_of_article.strftime("%B %-d, %Y")
    %br
    = image_tag article.image.url(:large), class: "pull-left" if article.image.exists?
    = article.body
%br
= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%h1.text-center
  = @article.title
%p
  = @article.date_of_article.strftime("%B %-d, %Y")
.image
  = image_tag @article.image.url(:large) if @article.image.exists?
%p
  = @article.body

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', root_path