config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/visit', to: 'static_pages#visit'

  resources :personnels, param: :uname

  resources :articles

  resources :affiliations

end

app/models/affiliation.rb
# == Schema Information
#
# Table name: affiliations
#
#  id                      :integer          not null, primary key
#  institute_name          :string(255)
#  website                 :string(255)
#  phone                   :string(255)
#  fax                     :string(255)
#  email                   :string(255)
#  parent_institutition_id :integer
#  created_at              :datetime
#  updated_at              :datetime
#  abv                     :string(255)
#

class Affiliation < ActiveRecord::Base
  has_many :employment_records

  validates :institute_name, presence: :true, uniqueness: true

  def website_url
    #binding.pry
    self.website || Rails.application.routes.url_helpers.affiliation_path(self.id)
  end
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :set_affiliation, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @affiliations = Affiliation.all
    respond_with(@affiliations)
  end

  def show
    respond_with(@affiliation)
  end

  def new
    @affiliation = Affiliation.new
    respond_with(@affiliation)
  end

  def edit
  end

  def create
    @affiliation = Affiliation.new(affiliation_params)
    @affiliation.save
    respond_with(@affiliation)
  end

  def update
    @affiliation.update(affiliation_params)
    respond_with(@affiliation)
  end

  def destroy
    @affiliation.destroy
    respond_with(@affiliation)
  end

  private
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

    def affiliation_params
      params.require(:affiliation).permit(:id, :institute_name, :website, :phone, 
          :fax, :email, :parent_institution_id, :abv
        )
    end 
end

app/views/affiliations/_form.html.haml
= form_for @affiliation do |f|
  .field
    =f.label :institute_name, "Name of Program/Center"
    =f.text_field :institute_name
  .field
    =f.label :website, "Website Url"
    =f.text_field :website
  .field
    =f.label :phone, "Main Phone Number of Program/Center"
    =f.text_field :phone
  .field
    =f.label :fax, "Fax Number"
    =f.text_field :fax
  .field
    =f.label :institute_name, "Name of Program/Center"
    =f.text_field :institute_name
  .field
    =f.label :website, "Website Url"
    =f.text_field :website

app/views/affiliations/edit.html.haml
%h1.text-center Edit the Information for a Program or Center

= render "form"

= link_to 'Show', affiliation_path(@affiliation)
\|
= link_to "Back", affiliations_path

app/views/affiliations/index.html.haml
%h1 Listing Programs and Centers

%table
  %tr
    %th Name


  - @affiliations.each do |affiliation|
    %tr
      %td= link_to(affiliation.institute_name, affiliation_path(affiliation))

app/views/affiliations/new.html.haml
%h1.text-center New Program or Center

= render 'form'

= link_to 'Back', affiliations_path

app/views/affiliations/show.html.haml
%p#notice= notice

%p
  %b=@affiliation.institute_name
%p
  %b Website Url
  = @affiliation.website
%p
  %b Phone Number
  = @affiliation.phone
%p
  %b Fax Number
  = @affiliation.fax
%p
  %b Institution Email
  = @affiliation.email