config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/visit', to: 'static_pages#visit'

  resources :personnels, param: :uname

  resources :articles

  resources :affiliations

end

app/models/personnel.rb
# == Schema Information
#
# Table name: personnels
#
#  id                  :integer          not null, primary key
#  uname               :string(255)
#  mailing_list        :boolean
#  formally_affiliated :boolean
#  retiree             :boolean
#  rostered            :boolean
#  first_name          :string(255)
#  last_name           :string(255)
#  salutation          :string(255)
#  notes               :text
#  research_interests  :text
#  skills_expertise    :text
#  bio                 :text
#  employee_id         :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#

class Personnel < ActiveRecord::Base
  attr_accessor :delete_image
  before_save :remove_image

  has_attached_file :avatar, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>"}, :default_url => "default_user.jpg"

  has_many :employment_records, dependent: :destroy
  has_many :academic_degrees, dependent: :destroy
  has_many :contact_details, dependent: :destroy
  has_many :contact_infos, dependent: :destroy
  has_many :websites, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_attachment_content_type :avatar, :content_type => /\Aimage/

  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/] 

  accepts_nested_attributes_for :employment_records, allow_destroy: true
  accepts_nested_attributes_for :academic_degrees, reject_if: lambda { |a| a[:year_awarded].blank? and !a[:in_progress] }, allow_destroy: true
  accepts_nested_attributes_for :contact_details, reject_if: lambda { |a| a[:job_title] and a[:organization]}, allow_destroy: true
  accepts_nested_attributes_for :contact_infos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :websites, reject_if: lambda { |a| a[:url].blank? }, allow_destroy: true

  def full_name
    self.first_name + " " + self.last_name
  end

  private
  
  def remove_image
    self.avatar = nil unless self.delete_image.to_i.zero?
  end

end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  before_action :set_personnel, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @personnels = Personnel.all
    respond_with(@personnels)
  end

  def show
    respond_with(@personnel, location: personnel_path(@personnel.uname))
  end

  def new
    @personnel = Personnel.new
    @personnel.employment_records.build
    @personnel.websites.build
    @personnel.academic_degrees.build
    @personnel.contact_infos.build
    @personnel.contact_details.build
    #binding.pry
    respond_with(@personnel)
  end

  def edit
  end

  def create
    @personnel = Personnel.new(personnel_params)
    @personnel.save
    respond_with(@personnel, location: personnel_path(@personnel.uname))
  end

  def update
    #binding.pry
    @personnel.update(personnel_params)
    respond_with(@personnel, location: personnel_path(@personnel.uname))
  end

  def destroy
    @personnel.destroy
    respond_with(@personnel)
  end

  private
    def set_personnel
      @personnel = Personnel.find_by_uname(params[:uname])
    end

    def personnel_params
      params.require(:personnel).permit(:uname, :mailing_list, :delete_image,
      :formally_affiliated, :retiree, :rostered, :first_name, :last_name, :avatar, 
      :salutation, :notes, :research_interests, :skills_expertise, :bio, :employee_id, 
      employment_records_attributes: [:id, :position_id, :affiliation_id, :start_date, :end_date, :_destroy],
      websites_attributes: [:id, :_destroy, :website_type_id, :url, :display_name],
      academic_degrees_attributes: [:id, :_destroy, :degree_type_id, :year_awarded, :in_progress, :university, :department],
      contact_details_attributes: [:id, :_destroy, :job_title, :organization, :address, :city, :state, :country, :zipcode, :phone, :email, :alt_phone, :alt_email],
      contact_infos_attributes: [:id, :_destroy, :display, :office_number, :phone_number, :email] 
      )
    end
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/views/personnels/_form.html.haml
= nested_form_for @personnel, url: {action: (@personnel.new_record? ? "create" : "update") } do |f|
  - if @personnel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@personnel.errors.count, "error")} prohibited this personnel from being saved:"
      %ul
        - @personnel.errors.full_messages.each do |msg|
          %li= msg
  #rootwizard
    .navbar
      .navbar-inner
        .container
          %ul.nav.nav-pills
            %li
              %a{href: "#tab1", data: {toggle: "tab"}}Person
            %li
              %a{href: "#tab2", data: {toggle: "tab"}}About
            %li
              %a{href: "#tab3", data: {toggle: "tab"}}Employee Info
            %li
              %a{href: "#tab4", data: {toggle: "tab"}}Academic Info
            %li
              %a{href: "#tab5", data: {toggle: "tab"}}Contact Info
    .tab-content
      #tab1.tab-pane
        %h3.text-center Identifying Info
        .row
          .col-md-3.col-md-offset-1
            .field
              = f.label :first_name
              <br>
              = f.text_field :first_name
            .field
              = f.label :last_name
              <br>
              = f.text_field :last_name
            .field
              = f.label :salutation
              <br>
              = f.text_field :salutation
            .field
              = f.label :uname, "Identikey Username"
              <br>
              = f.text_field :uname
          .col-md-3
            .field
              = f.check_box :mailing_list
              = f.label :mailing_list, "Add to Mailing List"
            .field
              = f.check_box :formally_affiliated
              = f.label :formally_affiliated, "Person is a grad-student or something"
            .field
              = f.check_box :retiree
              = f.label :retiree, "Person is a retiree of IBS"
            .field
              = f.check_box :rostered
              = f.label :rostered, "Person is officially rostered"
          .col-md-5
            .field
              = f.label :avatar, "Image"
              %br
              / = image_tag @personnel.avatar.url(:medium), class: "personnel_image"
              = f.file_field :avatar, accept: 'image/png,image/jpeg', class: "personnel_image"
              / determine if the image should be deleted
              = f.hidden_field :delete_image, value: "0"
              
      #tab2.tab-pane
        %h3.text-center About Personnel

        .field
          = f.label :bio
          <br>
          = f.text_area :bio
        .field
          = f.label :research_interests
          <br>
          = f.text_area :research_interests
        .field
          = f.label :skills_expertise
          <br>
          = f.text_area :skills_expertise
        .field
          = f.label :notes
          <br>
          = f.text_area :notes
      #tab3.tab-pane
        %h3.text-center Employee Information
        .field
          = f.label :employee_id, "Employee/Staff Id"
          = f.text_field :employee_id
        = f.fields_for :employment_records do |er_form|
          .field
            = er_form.label :position_id, "Employee's Position"
            = er_form.collection_select :position_id, Position.order(:title), :id, :title
          .field
            = er_form.label :affiliation_id, "Affiliation"
            = er_form.collection_select :affiliation_id, Affiliation.order(:institute_name), :id, :institute_name
          .field
            = er_form.label :start_date, "Started Employment"
            = er_form.date_select :start_date, order: [:month, :year], start_year: 1995
          .field
            = er_form.label :end_date, "End Employment (If any)"
            = er_form.date_select :end_date, order: [:month, :year], include_blank: true
          = er_form.link_to_remove "Delete Employee Record"
        = f.link_to_add "Add another employement record", :employment_records
      #tab4.tab-pane
        %h3.text-center Academic Information
        = f.fields_for :websites do |web_form|
          .field
            = web_form.label :url
            = web_form.text_field :url
          .field
            = web_form.label :display_name
            = web_form.text_field :display_name
          .field
            = web_form.label :website_type_id, "Type of Website"
            = web_form.collection_select :website_type_id, WebsiteType.order(:web_type), :id, :web_type
            %br
            = web_form.link_to_remove "Delete Website"
        = f.link_to_add "Add another website record", :websites
        = f.fields_for :academic_degrees do |ac_form|
          .field
            = ac_form.label :degree_type_id, "Type of Degree"
            = ac_form.collection_select :degree_type_id, DegreeType.order(:degree_type), :id, :degree_type
          .field
            = ac_form.label :year_awarded, "Year Awarded"
            = ac_form.text_field :year_awarded
          OR
          .field
            = ac_form.check_box :in_progress
            = ac_form.label :in_progress
          .field
            = ac_form.label :university
            = ac_form.text_field :university
          .field
            = ac_form.label :department
            = ac_form.text_field :department
          = ac_form.link_to_remove "Delete Academic Degree"
        = f.link_to_add "Add another academic degree", :academic_degrees
      #tab5.tab-pane
        %h3.text-center Professional and Personal Contact
        = f.fields_for :contact_details do |cd_form|
          .field
            = cd_form.label :job_title
            = cd_form.text_field :job_title
          .field
            = cd_form.label :organization
            = cd_form.text_field :organization
          .field
            = cd_form.label :address
            <br>
            = cd_form.text_area :address
          .field
            = cd_form.label :city
            = cd_form.text_field :city
          .field
            = cd_form.label :state
            = cd_form.text_field :state
          .field
            = cd_form.label :country
            = cd_form.text_field :country
          .field
            = cd_form.label :zipcode
            = cd_form.text_field :zipcode
          .field
            = cd_form.label :phone
            = cd_form.text_field :phone
          .field
            = cd_form.label :email
            = cd_form.text_field :email
          .field
            = cd_form.label :alt_phone
            = cd_form.text_field :alt_phone
          .field
            = cd_form.label :alt_email
            = cd_form.text_field :alt_email
          = cd_form.link_to_remove "Delete Contact Details"
        = f.link_to_add "Add another contact details form", :contact_details
        = f.fields_for :contact_infos do |ci_form|
          .field
            = ci_form.check_box :display
            = ci_form.label :display
          .field
            = ci_form.label :office_number
            = ci_form.text_field :office_number
          .field
            = ci_form.label :phone_number
            = ci_form.text_field :phone_number
          .field
            = ci_form.label :email
            = ci_form.text_field :email
          = ci_form.link_to_remove "Delete Contact Info"
        = f.link_to_add "add another contact info form", :contact_infos
      %ul.pager.wizard
        %li.previous
          %a{href:"#"}Previous
        %li.next
          %a{href:"#"}Next
      .actions
        = f.submit 'Save'
:coffee
  -# This is here because javascript files served from the asset folder do not have
  -# Access to controller class instance variables

  img_source = "#{defined?(@personnel) && @personnel.avatar.exists? ? @personnel.avatar.url(:medium) : image_url('default_user.jpg')}"
  $(".personnel_image").fileinput initialPreview: ["<img src='"+img_source+"' class=\'file-preview-image\' alt=\'Avatar\' title=\'Avatar\'>"], showUpload: false
  
  $('.personnel_image').on 'filecleared', (event) -> 
    $('#personnel_delete_image').val "1"
  $('.personnel_image').on 'fileloaded', (event) -> 
    $('#personnel_delete_image').val "0"

app/views/personnels/edit.html.haml
%h1 Editing personnel

= render 'form'

= link_to 'Show', personnel_path(@personnel.uname)
\|
= link_to 'Back', personnels_path

app/views/personnels/index.html.haml
%h1.text-center IBS Directory

%table.table.table-striped
  %tr
    %th Name
    %th Email
    %th Phone
    %th IBS Affiliation


  - @personnels.each do |personnel|
    %tr
      %td= link_to personnel.full_name, personnel_path(personnel.uname)
      %td
        - personnel.contact_infos.each do |ci|
          = ci.email if ci.display?
      %td
        - personnel.contact_infos.each do |ci|
          = ci.phone if ci.display?
      %td
        - personnel.employment_records.each_with_index do |er, index|
          #{er.position.title}, #{link_to(er.affiliation.institute_name, er.affiliation.website_url)}
          - unless index == (personnel.employment_records.size-1)
            %br

      / %td #{link_to 'Show', personnel_path(personnel.uname)} | #{link_to 'Edit', edit_personnel_path(personnel.uname)} | #{link_to 'Destroy', personnel.uname, :method => :delete, :data => { :confirm => 'Are you sure?' }}


%br

= link_to 'New Personnel', new_personnel_path

app/views/personnels/new.html.haml
%h1.text-center New personnel

= render 'form'

= link_to 'Back', personnels_path

app/views/personnels/show.html.haml
%p#notice= notice

= image_tag @personnel.avatar.url(:medium) if @personnel.avatar.exists?
%p
  %b Uname:
  = @personnel.uname
%p
  %b Mailing list:
  = @personnel.mailing_list
%p
  %b Formally affiliated:
  = @personnel.formally_affiliated
%p
  %b Retiree:
  = @personnel.retiree
%p
  %b Rostered:
  = @personnel.rostered
%p
  %b First name:
  = @personnel.first_name
%p
  %b Last name:
  = @personnel.last_name
%p
  %b Salutation:
  = @personnel.salutation
%p
  %b Notes:
  = @personnel.notes
%p
  %b Research interests:
  = @personnel.research_interests
%p
  %b Skills expertise:
  = @personnel.skills_expertise
%p
  %b Bio:
  = @personnel.bio
%p
  %b Employee:
  = @personnel.employee_id

= link_to 'Edit', edit_personnel_path(@personnel.uname)
\|
= link_to 'Back', personnels_path