config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/visit', to: 'static_pages#visit'

  resources :personnels, param: :uname

  resources :articles

  resources :affiliations

end

app/views/layouts/_footer.html.haml
#footer
  .section
    .span-14.left
      .address
        %span.name
          %a{href: "http://www.colorado.edu/ibs/"}Institue of Behavioral Science
        %br
        1440 15th Street, Boulder, CO 80302
        %br
        303-492-8147
        %br
        Fax: 303-492-2151
    .span-15.right.details
      %p
        %a{href:"http://www.colorado.edu/ibs/"}Institue of Behavioral Science (IBS)
        %br
        %a{href:"http://www.colorado.edu/ibs/contact.html"}Contact IBS
        %br
        %a{href:"http://www.colorado.edu/ibs/intranet/"}IBS Intranet
    %br.clear
  .section.section-sub
    %p
      %a.legal{href:"http://www.colorado.edu/about/legal.html"}Terms of Use
      %br
      %a.legal{href:"http://www.colorado.edu/privacy/"}Privacy Policy
    %p
      %a{href:"http://www.colorado.edu/"}University of Colorado Boulder
      %br  &#xa9; The Regents of the University of Colorado

app/views/layouts/_header.html.haml
#header
  #skipnav
    %a{href: "#content"} Skip to Main Content
  .section
    %h1
      %a{href: "http://www.colorado.edu/ibs/"}Institute of Behavioral Science (IBS)
    #search
      #culinks
        %strong CU:
        %a{href: "http://www.colorado.edu/"}Home &#x2022;
        %a{href: "http://www.colorado.edu/atoz/"}A to Z &#x2022;
        %a{href: "http://www.colorado.edu/campusmap"}Campus Map
      #searchform
        %form{action: "http://www.colorado.edu/search/custom/searchdirect.cgi", method: "post"}
          #inputwrapper
            %input.searchstring{type: 'text', name:'searchstring', value:'Search this site', onfocus:"this.value=''"}
            %input{type:'hidden', name:'searchtype', value:'www.colorado.edu/ibs'}
          %input{type:"image", src:"/assets/submit.png", value:"Submit", size:"22,23"}

app/views/layouts/_navbar.html.haml
.navigation 
  .section
    %nav{role: "navigation", class: "navbar"}
      .container-fluid
        / .navbar-header
        /   %button{type: "button", class: "navbar-toggle collapsed", data: {toggle: "collapse", target:"#bs-example-navbar-collapse-1"}}
        /     %span{class: "sr-only"}Toggle navigation
        /     %span{class: "icon-bar"}
        /     %span{class: "icon-bar"}
        /     %span{class: "icon-bar"}
        /   = link_to root_path do
        /     %span.glyphicon.glyphicon-home

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to root_path do
                %span.glyphicon.glyphicon-home
            %li.dropdown
              = link_to about_path do
                About
                %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li
                  = link_to "About", about_path
                %li
                  = link_to "Contact", contact_path
                %li
                  = link_to "Visit", visit_path
            %li.dropdown
              = link_to "#" do
                News
                %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li
                  = link_to "IBS News", "#"
                %li
                  = link_to "News Archive", "#"
                %li
                  = link_to "News Letter", "#"
                %li
                  = link_to "Social Gatherings", "#"
            %li.dropdown
              = link_to "#" do
                Colloquia
                %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li
                  = link_to "Upcoming Colloquia", "#"
                %li
                  = link_to "Past Colloquia", "#"
                %li
                  = link_to "Video Links", "#"
                %li
                  = link_to "Room Reservations", "#"
            %li.dropdown
              = link_to "#" do
                Publications
                %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li
                  = link_to "Publications", "#"
                %li
                  = link_to "Working Papers", "#"
            %li
              = link_to "Graduate Training", "#"
            %li
              = link_to "Computing & Research Services", "#"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Institute of Behavioral Sciences
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "layouts/header"
    = render partial: "layouts/navbar"
    #main.background_gradient
      .section
        = yield
    = render partial: "layouts/footer"